apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache  # This label is specific to this Deployment
        # The environment label will be added by Kustomize
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: apache
          image: vsrekul/apache:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs/index.html
              subPath: index.html
      volumes:
        - name: html-volume
          configMap:
            name: apache-index
