apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1  
  template:
    metadata:      
    spec:
      containers:
        - name: apache
          image: your-docker-repo/apache:latest
          ports:
            - containerPort: 80
